API_PREFIX = "/api"
WEBSOCKET_PATH = "/ws/nodes"
PROTOCOL_VERSION = 1
PROTOCOL_MINOR_VERSION = 0
SESSION_COOKIE_NAME = "dssc_session"
CSRF_COOKIE_NAME = "dssc_csrf"
CSRF_HEADER_NAME = "X-CSRF-Token"

DEFAULT_SESSION_TTL_SECONDS = 60 * 60 * 12
DEFAULT_CSRF_TTL_SECONDS = 60 * 60 * 12
DEFAULT_SIGNED_DOWNLOAD_TTL_SECONDS = 60 * 10
DEFAULT_COMMAND_ACK_TIMEOUT_SECONDS = 5

DEFAULT_HEARTBEAT_SWEEP_INTERVAL_SECONDS = 10
DEFAULT_HEARTBEAT_STALE_AFTER_SECONDS = 45
DEFAULT_HEARTBEAT_OFFLINE_AFTER_SECONDS = 90

DEFAULT_ALLOWED_UPLOAD_EXTENSIONS = (".mp3", ".wav", ".aac", ".m4a", ".ogg")
DEFAULT_ALLOWED_UPLOAD_MIME_TYPES = (
    "audio/mpeg",
    "audio/wav",
    "audio/x-wav",
    "audio/aac",
    "audio/mp4",
    "audio/ogg",
)

DEFAULT_SCHEDULER_INTERVAL_MINUTES = 15
DEFAULT_LOGIN_WINDOW_SECONDS = 60 * 5
DEFAULT_LOGIN_LOCKOUT_SECONDS = 60 * 10
DEFAULT_LOGIN_MAX_ATTEMPTS = 5
DEFAULT_EVENT_RETENTION_DAYS = 30
DEFAULT_INACTIVE_SPOT_RETENTION_DAYS = 14
DEFAULT_RETENTION_SWEEP_INTERVAL_HOURS = 12
DEFAULT_ENROLLMENT_CODE_LENGTH = 6
DEFAULT_ENROLLMENT_TTL_SECONDS = 60 * 30
